version: '3.8'  # Versión de docker-compose que usaremos

services:
  # Definimos nuestro servicio de MySQL
  mysql:
    image: mysql:8.0  # Usamos la imagen oficial de MySQL versión 8.0
    container_name: library_mysql  # Nombre que le damos al contenedor
    environment:  # Variables de entorno para configurar MySQL
      MYSQL_ROOT_PASSWORD: Colombia2025.  # Contraseña para el usuario root
      MYSQL_DATABASE: library_db  # Nombre de la base de datos que se creará
      MYSQL_USER: jotazz  # Usuario que se creará
      MYSQL_PASSWORD: Colombia2025.  # Contraseña para el usuario
    ports:
      - "3306:3306"  # Mapeo de puertos - Puerto_Local:Puerto_Contenedor
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen para persistir los datos
    restart: always  # Reinicia el contenedor si se detiene

volumes:
  mysql_data:  # Definición del volumen para persistir datos
    name: library_mysql_data  # Nombre específico para el volumen
